# Generated by Django 6.0 on 2025-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hu'),
            preserve_default=False,
        ),
    ]
