# Generated by Django 6.0 on 2025-12-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_assign_books_to_first_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audience',
            field=models.TextField(blank=True, help_text='The target audience for the book', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='core_topic',
            field=models.TextField(blank=True, help_text='The core topic of the book', null=True),
        ),
    ]
