# Generated by Django 6.0 on 2025-12-18 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_bookcollaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('insertion', 'Insertion'), ('deletion', 'Deletion'), ('replacement', 'Replacement')], default='replacement', max_length=20)),
                ('start_position', models.PositiveIntegerField(help_text='Start position in original text')),
                ('end_position', models.PositiveIntegerField(help_text='End position in original text (for deletions/replacements)')),
                ('old_text', models.TextField(blank=True, help_text='Original text being replaced/deleted', null=True)),
                ('new_text', models.TextField(blank=True, help_text='New text being inserted/replacing', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('talking_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_changes', to='pilot.talkingpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_position', 'created_at'],
                'indexes': [models.Index(fields=['talking_point', 'status'], name='pilot_conte_talking_6a05f9_idx'), models.Index(fields=['user', 'status'], name='pilot_conte_user_id_55513e_idx')],
            },
        ),
    ]
