# Generated by Django 6.0 on 2026-01-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0009_contentchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchange',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment explaining the suggestion', null=True),
        ),
    ]
