# Generated by Django 6.0 on 2026-01-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0010_add_comment_to_contentchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchange',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Optional comment explaining the suggestion'),
        ),
        migrations.CreateModel(
            name='CollaborationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('steps', models.TextField(default='[]')),
                ('step_client_ids', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talking_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collab_state', to='pilot.talkingpoint')),
            ],
            options={
                'db_table': 'pilot_collaborationstate',
            },
        ),
    ]
