# Generated by Django 6.0 on 2026-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0011_alter_contentchange_comment_collaborationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchange',
            name='prosemirror_from',
            field=models.PositiveIntegerField(default=0, help_text="ProseMirror 'from' position in the document"),
        ),
        migrations.AddField(
            model_name='contentchange',
            name='prosemirror_to',
            field=models.PositiveIntegerField(default=0, help_text="ProseMirror 'to' position in the document"),
        ),
        migrations.AlterField(
            model_name='contentchange',
            name='end_position',
            field=models.PositiveIntegerField(default=0, help_text='End position in normalized plain text (legacy)'),
        ),
        migrations.AlterField(
            model_name='contentchange',
            name='start_position',
            field=models.PositiveIntegerField(default=0, help_text='Start position in normalized plain text (legacy)'),
        ),
    ]
