# Generated by Django 6.0 on 2026-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0012_contentchange_prosemirror_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchange',
            name='step_json',
            field=models.JSONField(blank=True, help_text='ProseMirror step JSON for accurate change application', null=True),
        ),
        migrations.AlterField(
            model_name='contentchange',
            name='new_text',
            field=models.TextField(blank=True, help_text='New text being inserted/replacing (for display)', null=True),
        ),
        migrations.AlterField(
            model_name='contentchange',
            name='old_text',
            field=models.TextField(blank=True, help_text='Original text being replaced/deleted (for display)', null=True),
        ),
    ]
