# Generated by Django 6.0 on 2026-01-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0013_contentchange_step_json_alter_contentchange_new_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentchange',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contentchange',
            name='pilot_conte_talking_6a05f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentchange',
            name='pilot_conte_user_id_55513e_idx',
        ),
        migrations.AlterField(
            model_name='contentchange',
            name='step_json',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='end_position',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='new_text',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='old_text',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='prosemirror_from',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='prosemirror_to',
        ),
        migrations.RemoveField(
            model_name='contentchange',
            name='start_position',
        ),
    ]
