# Generated by Django 6.0 on 2026-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0015_make_step_json_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchange',
            name='step_json',
            field=models.JSONField(),
        ),
    ]
