# Generated by Django 6.0 on 2026-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0017_add_parent_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audience_tag',
            field=models.JSONField(blank=True, help_text="Emotional audience type tag: {primary: 'RED'|'BLUE'|'GREEN'|'YELLOW', secondary?: 'RED'|'BLUE'|'GREEN'|'YELLOW', confidence: float, reasoning: string}", null=True),
        ),
    ]
