# Generated by Django 6.0 on 2026-01-14 12:30

import pilot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0018_add_audience_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chapterasset',
            name='file',
            field=models.FileField(upload_to=pilot.models.chapter_asset_upload_path),
        ),
    ]
