# Generated by Django 6.0 on 2026-01-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0019_increase_book_title_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositioningBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_text', models.TextField(help_text='Full aggregated positioning brief')),
                ('pillar_summaries', models.JSONField(help_text='Dict of pillar_slug -> summary')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='positioning_brief', to='pilot.book')),
            ],
        ),
        migrations.CreateModel(
            name='PositioningPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='LOCKED', max_length=20)),
                ('depth_score', models.FloatField(default=0.0, help_text='0-100 score for answer quality/depth')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary when pillar is complete', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positioning_pillars', to='pilot.book')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('book', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PillarChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('state_emission', models.JSONField(blank=True, help_text='Progress state emitted after assistant turns', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pilot.positioningpillar')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
