# Generated by Django 6.0 on 2026-01-29 18:43

import django.db.models.deletion
import pilot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0020_positioningbrief_positioningpillar_pillarchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PillarAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pilot.models.pillar_asset_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content from the file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pilot.positioningpillar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillar_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
