# Generated by Django 6.0 on 2026-02-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0021_add_pillar_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='spelling_convention',
            field=models.CharField(choices=[('us', 'American English (US)'), ('uk', 'British English (UK)'), ('auto', 'Auto-detect from content')], default='auto', help_text='Preferred spelling convention for the book (US/UK English)', max_length=10),
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='The term as it appears in the text', max_length=255)),
                ('preferred_spelling', models.CharField(blank=True, help_text='Preferred spelling if different from term (e.g., for case sensitivity)', max_length=255, null=True)),
                ('definition', models.TextField(blank=True, help_text='Optional definition or explanation of the term', null=True)),
                ('do_not_change', models.BooleanField(default=True, help_text='If true, this term should never be flagged for spelling corrections')),
                ('category', models.CharField(choices=[('brand', 'Brand/Company Name'), ('framework', 'Framework/Methodology'), ('technical', 'Technical Term'), ('acronym', 'Acronym/Abbreviation'), ('proper_noun', 'Proper Noun'), ('other', 'Other')], default='other', help_text='Category of the term', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='pilot.book')),
            ],
            options={
                'ordering': ['term'],
                'unique_together': {('book', 'term')},
            },
        ),
    ]
