from django.urls import path
from .views import (
    createOutline,
    generate_followup_question,
    generate_text,
    add_user_context,
    list_books,
    create_book,
    get_book,
    create_chapter,
    update_chapter,
    delete_chapter,
    create_section,
    update_section,
    delete_section,
    create_talking_point,
    update_talking_point,
    delete_talking_point,
    upload_chapter_asset,
    list_chapter_assets,
    ask_chat_question,
    comments_list_create,
    comment_detail,
    chat_with_changes,
    quick_text_action,
    book_collaborators,
    remove_collaborator,
    content_changes_list_create,
    content_change_detail,
    collab_receive_steps,
    collab_get_state,
    run_book_checks_endpoint,
)

urlpatterns = [
    path("create_outline/", createOutline),
    path("generate_followup/", generate_followup_question),
    path("generate_text/", generate_text),
    path("user_context/", add_user_context),
    path("books/", list_books),
    path("books/create/", create_book),
    path("books/<int:pk>/", get_book),
    path("books/<int:book_id>/chapters/", create_chapter),
    path("chapters/<int:chapter_id>/", update_chapter),
    path("chapters/<int:chapter_id>/delete/", delete_chapter),
    path("chapters/<int:chapter_id>/sections/", create_section),
    path("sections/<int:section_id>/", update_section),
    path("sections/<int:section_id>/delete/", delete_section),
    path("sections/<int:section_id>/talking_points/", create_talking_point),
    path("talking_points/<int:tp_id>/", update_talking_point),
    path("talking_points/<int:tp_id>/delete/", delete_talking_point),
    path("assets/upload/", upload_chapter_asset),
    path("assets/", list_chapter_assets),
    path("chat/", ask_chat_question),
    path("chat/with-changes/", chat_with_changes),
    path("quick-action/", quick_text_action),
    path("comments/", comments_list_create),
    path("comments/<int:comment_id>/", comment_detail),
    path("books/<int:book_id>/collaborators/", book_collaborators),
    path("books/<int:book_id>/collaborators/<int:collaborator_id>/", remove_collaborator),
    path("talking_points/<int:talking_point_id>/changes/", content_changes_list_create),
    path("changes/<int:change_id>/", content_change_detail),
    path("talking_points/<int:talking_point_id>/collab/", collab_receive_steps),
    path("talking_points/<int:talking_point_id>/collab/state/", collab_get_state),
    path("books/<int:book_id>/checks/", run_book_checks_endpoint),
]